// Constants
#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE  "Zombies"

#define SPRITE_PLAYER_BITMAP_FILE_NAME "hero_sprite.bmp"
#define SPRITE_PLAYER_START_X  0.0f
#define SPRITE_PLAYER_START_Y  0.0f
#define SPRITE_PLAYER_IMAGE_X  6
#define SPRITE_PLAYER_IMAGE_Y  6
#define SPRITE_PLAYER_IMAGE_WIDTH   34
#define SPRITE_PLAYER_IMAGE_HEIGHT  40
#define SPRITE_PLAYER_SPEED  100.0

#define ZOMBIE_SPRITE_BITMAP_FILE_NAME  "zombie.bmp"
#define ZOMBIE_SPRITE_START_X  250.0f
#define ZOMBIE_SPRITE_START_Y  250.0f
#define ZOMBIE_SPRITE_IMAGE_X  46
#define ZOMBIE_SPRITE_IMAGE_Y  49
#define ZOMBIE_SPRITE_IMAGE_WIDTH  46
#define ZOMBIE_SPRITE_IMAGE_HEIGHT  49
#define ZOMBIE_SPRITE_SPEED  50.0


#define BACKGROUND_RED  0
#define BACKGROUND_GREEN  0
#define BACKGROUND_BLUE  0

#define TRANSPARENT_RED  0
#define TRANSPARENT_GREEN  255
#define TRANSPARENT_BLUE  0

